### PR TITLE
move coredump to /tmp

### PR DESCRIPTION
**Pull request by Kyle-Kyle**

### CODE REVIEW

**Comment by zardus** [comment]
For some reason github doesn't realize I rebase-and-merged this....

**Comment by ltfish** [comment]
What is the rationale behind this change? @Kyle-Kyle

**Comment by Kyle-Kyle** [comment]
Because of `archr` I guess. Before this change, coredumps will be placed in the the current folder which seems to bring some trouble to `archr`. So Yan implement a contextmanager for tracer to execute tracing in a temp directory which breaks things. So we decided to move the coredump to `/tmp`.

**Comment by ltfish** [comment]
Unfortunately, the current solution hard-codes the core file path to `/tmp/`, which breaks multithreading/multiprocess tracing.  As far as I see it, a better solution is to pass to Qemu a command-line argument of where the core file should go, and if that argument is not provided, put the core file in the current working directory. What do you think? Do you want to implement it?

**Comment by Kyle-Kyle** [comment]
I agree that's a better solution. But I wonder how multithreading was processed before? All coredumps are in current directory is the same to those in `/tmp`.

**Comment by zardus** [comment]
We made a temporary dir to cd into before, so every invocation of tracer would be independent in that sense. archr accomplishes something similar if using the DockerImageTarget, because you can have different containers for different runs, but fish is correct in the general sense.

**Comment by Kyle-Kyle** [comment]
@ltfish About the implementation. I'm not sure whether I can do that, but I will give it a try this weekend.

**Comment by ltfish** [comment]
> All coredumps are in current directory is the same to those in `/tmp`.

PovSim was creating a temporary directory for each challenge binary (using your favorite `mkstemp` ;) ) and then making that temporary directory the current working directory of the challenge binary.

**Comment by ltfish** [comment]
> I'm not sure whether I can do that

Of course you can! Let me know if you have questions. It should be straightforward. Good luck!

**Comment by Kyle-Kyle** [comment]
One possible temp fix is to add pid in the coredump name, it will be easy. But let me try the clean solution first.

**Comment by ltfish** [comment]
I agree, but it'll be great if we can solve this problem for good :)

**Comment by zardus** [comment]
The corefile already has the PID, I think. Here's a sample:
/tmp/qemu_arbitrary_transmit_20181103-105407_3624.core. Looks like it is
"qemu_"+binary_name+"_"+date+"_"+time+"_"+pid+".core"

**Comment by Kyle-Kyle** [comment]
@zardus I thought there were milliseconds lol.

**Comment by ltfish** [comment]
@zardus Correct. I was half-way patching PovSim locally before I realized that the better solution is to not hardcode an absolute path for coredumps.

**Pull request closed without merging**
