### PR TITLE
Wip/halfway tracing

### PR DESCRIPTION
**Pull request by Kyle-Kyle**
CHANGE LIST
1. NT_FILE support in core dump
2. allow generating coredump of a live process without killing it
3. allow recording traces after a certain address
4. disable block break up in mips

### CODE REVIEW

**Comment by rhelmot** [comment]
Here's an experiment - can we roll back the first set of changes we made, the one that makes it dump the read-only executable sections in full, and see if once we have these changes in that everything will load correctly? If it works, it'll decrease the size of the core files by a ton.

**Comment by Kyle-Kyle** [comment]
yeah. that makes sense. We pull the whole remote dependencies to local machines in archr anyway

**Comment by Kyle-Kyle** [comment]
@rhelmot I revert the patch and everything still works.

**Comment by rhelmot** [comment]
perf

**Pull request merged**
